default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_checkpoint_challenge_development

test:
  <<: *default
  database: rails_checkpoint_challenge_test

production:
  <<: *default
  database: rails_checkpoint_challenge_production
  username: rails_checkpoint_challenge
  password: <%= ENV['RAILS_CHECKPOINT_CHALLENGE_DATABASE_PASSWORD'] %>
